import chemical_reaction_networks_autocatalytic_networks_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace chemical_reaction_networks_autocatalytic_networks_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end chemical_reaction_networks_autocatalytic_networks_foundation_canonical_lane_mathlib
end HautevilleHouse
